@startuml DomainModel

class TierMaker {}
class TierList {}
class Tier {}
class Element {}
class ElementList {}

TierMaker *-- TierList 
TierMaker *-- ElementList 

TierList o-- Tier 
ElementList o-- "*" Element

ElementList <|-- Tier

@enduml